export const icons = [
"more_horiz_40px.svg",
"more_horiz_24px.svg",
"more_horiz_20px.svg",
"more_horiz_48px.svg",
"chevron_right_40px.svg",
"chevron_right_24px.svg",
"chevron_right_20px.svg",
"chevron_right_48px.svg",
"more_40px.svg",
"more_24px.svg",
"more_20px.svg",
"more_48px.svg",
"cancel_40px.svg",
"cancel_24px.svg",
"cancel_20px.svg",
"cancel_48px.svg",
"edit_40px.svg",
"edit_24px.svg",
"edit_20px.svg",
"edit_48px.svg",
"search_40px.svg",
"search_24px.svg",
"search_20px.svg",
"search_48px.svg",
"home_40px.svg",
"home_24px.svg",
"home_20px.svg",
"home_48px.svg",
"info_40px.svg",
"info_24px.svg",
"info_20px.svg",
"info_48px.svg",
];
export type AppIcon = 
"cancel"|
"chevron_right"|
"edit"|
"home"|
"info"|
"more"|
"more_horiz"|
"search"|
undefined;
